### ISSUE TITLE
Get a translation programatically 

### ISSUE THREAD

**Issue by SaidTayebi** [dhoko/angular-ngBabelfish#49]
Hi there,
Is there a way to get a translation for a value programmatically (in JavaScript not HTML) ?

Thank you.

**Comment by dhoko** [comment]
Hi,

Yup you can cf [service babelfish](https://github.com/dhoko/angular-ngBabelfish#service-babelfish).

**Comment by SaidTayebi** [comment]
Thanks! Works fine 😊
